### ISSUE TITLE
Links Mouse and Keyboard to iPad instead of extending the display

### ISSUE THREAD

**Issue by vratclarkson** [kovstas/alfred-sidecar#2]
Hi there

Can you modify to consider this case?

Thanks

**Comment by kovstas** [comment]
Hi 

Yes, I understand your problem, but unfortunately, I can’t test it properly on my side. I’ve made some changes that should fix the issue. Could you please check if it works for you? Just download and install this release https://github.com/kovstas/alfred-sidecar/releases/tag/v1.3

**Comment by uloco** [comment]
Still happening with 1.3 unfortunately

**Comment by uloco** [comment]
I found out that it works when the ipad is not unlocked, so there is no connect keyboard entry in the popup menu, but just the extend display one. Then it connects successfully. I tried to debug the popup but could not find a way since I have no clue of applescript, nor did any help of chatgpt or claude bring any successfull results. apple inspector shows that the values of the popup are correct but for whatever reason the script still just selects the first value in the popup.

**Comment by kovstas** [comment]
Thank you for your feedback! I will try to find the cause, I see that the attributes of these buttons are different that can be used as a way to identify the correct one.

**Comment by kovstas** [comment]
@uloco I have just released a new version that should fix the issue. Could you please check if it works for you? https://github.com/kovstas/alfred-sidecar/releases/tag/v1.4

**Comment by uloco** [comment]
this works, thank you so much! :)))
